### ISSUE TITLE
cisco.nxos.nxos_bgp_global module timers and no shutdown

### ISSUE THREAD

**Issue by KennyVdN** [ansible-collections/cisco.nxos#240]
##### SUMMARY

neighbor timers are not set and neighbor remains in shutdown
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

      cisco.nxos.nxos_bgp_global:

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.6
  config file = /home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg
  configured module search path = ['/home/kvandenn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kvandenn/Ansible/envs/vEnvAnsible2.9.6-P3.7.9/lib/python3.7/site-packages/ansible
  executable location = /home/kvandenn/Ansible/envs/vEnvAnsible2.9.6-P3.7.9/bin/ansible
  python version = 3.7.9 (default, Jan  7 2021, 10:07:14) [GCC 7.5.0]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_GATHERING(/home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg) = ['/home/kvandenn/Ansible
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/kvandenn/Ansible/ansible-scripts/kenny01/.ansi
HOST_KEY_CHECKING(/home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg) = auto_legacy_silent
RETRY_FILES_ENABLED(/home/kvandenn/Ansible/ansible-scripts/kenny01/sva-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```paste below
sbx-n9kv# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2020, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Nexus 9000v is a demo version of the Nexus Operating System

Software
  BIOS: version 
 NXOS: version 9.3(5)
  BIOS compile time:  
  NXOS image file is: bootflash:///nxos.9.3.5.bin
  NXOS compile time:  7/20/2020 20:00:00 [07/21/2020 06:30:11]


Hardware
  cisco Nexus9000 C9500v Chassis ("Supervisor Module")
  Intel(R) Xeon(R) CPU E5-4669 v4 @ 2.20GHz with 7939724 kB of memory.
  Processor Board ID 9FJTZNHQ62X

  Device name: sbx-n9kv
  bootflash:    4287040 kB
Kernel uptime is 2 day(s), 20 hour(s), 7 minute(s), 2 second(s)

Last reset 
  Reason: Unknown
  System version: 
  Service: 

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
        
sbx-n9kv# 

```
##### STEPS TO REPRODUCE

--> no timers set, neighbor admin down.

```yaml
    - name: Make sure BGP routing is setup
      cisco.nxos.nxos_bgp_global:
        config:
          as_number: "{{ bgp_edge_as | string }}"
          vrfs:
          - vrf: "{{ CUST_VRF }}"
            neighbors: 
            - neighbor_address: "{{ bgp_pe_ip }}"
              description: "{{ bgp_pe_desc }}"
              remote_as: "{{ IPC_AS | string }}"
              shutdown: no
              timers:
                holdtime: 15
                keepalive: 5

```

##### EXPECTED RESULTS

```paste below
sbx-n9kv# sh run | sect bgp
feature bgp
router bgp 65535
  vrf Kenny001VRF
    neighbor 1.1.1.1
      remote-as 65511
      description BGP to PE1
      timers 5 15

```
##### ACTUAL RESULTS

```paste below
sbx-n9kv# sh run | sect bgp
feature bgp
router bgp 65535
  vrf Kenny001VRF
    neighbor 1.1.1.1
      remote-as 65511
      description BGP to PE1
      shutdown


```

**Comment by NilashishC** [comment]
@KennyVdN Thanks for opening this ticket. The patch in #242 should fix this.

**Comment by KennyVdN** [comment]
Should #242 already be available for install using ansible-galaxy collection install cisco.nxos --force?
Doing this did not fix it for me, I just tried...
Thx
Kenny
