### ISSUE TITLE
nxos_reboot hangs for duration of the ansible_command_timeout

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/cisco.nxos#25]
##### SUMMARY

When ansible_command_timeout is configured with `nxos_reboot`, the task will hang for the duration of that timeout value. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_reboot
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/bdudas/dev-net/nxos/ansible.cfg
  configured module search path = ['/Users/bdudas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/bdudas/dev-net/nxos/ansible.cfg) = ['/Users/bdudas/dev-net/inventory/hosts']
DEPRECATION_WARNINGS(/Users/bdudas/dev-net/nxos/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/bdudas/dev-net/nxos/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/bdudas/dev-net/nxos/ansible.cfg) = False
```

##### OS / ENVIRONMENT

NXOS: version 9.3(3)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: nxos
  gather_facts: false

  tasks:
    - name: get {{ inventory_hostname }} starting uptime
      cisco.nxos.nxos_command:
        commands: show system uptime
      register: uptime_start

    - name: debug starting uptime
      debug:
        var: uptime_start.stdout_lines

    - name: reboot {{ inventory_hostname }}
      cisco.nxos.nxos_reboot:
        confirm: true
      vars:
        ansible_command_timeout: 300

    - name: wait for {{ inventory_hostname }} to reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        sleep: 5
        timeout: 300
      delegate_to: localhost

    - name: get {{ inventory_hostname }} uptime
      cisco.nxos.nxos_command:
        commands: show system uptime
      register: uptime_finish

    - name: debug finishing uptime
      debug:
        var: uptime_finish.stdout_lines
...
```

##### EXPECTED RESULTS

Same behavior as seen with other nxos modules where the job would move to the next task when completed and not hang for the duration of that timeout.

**Comment by feisa** [comment]
@NilashishC  any update on this?

**Comment by NilashishC** [comment]
@benjdudas @feisa I tried to reproduce this with an unreasonably high command_timeout value, but the reboot task run didn't hang until the timeout was reached, instead it completed as soon as the system rebooted. Could you try with the latest cisco.nxos collection and ansible.netcommon to check if this issue still persists?

**Comment by NilashishC** [comment]
@benjdudas @feisa This was most likely an issue in network_cli that got fixed sometime back in ansible.netcommon. Pulling network_cli from ansible.netcommon collection (using `ansible_network_os: ansible.netcommon.network_cli`) instead of the Ansible 2.9 network_cli should fix this. We're trying to locate the patch that fixed this in the collection and backport it to 2.9.

**Comment by feisa** [comment]
Im having the issue in 2.10 so are you telling me to use a collection?

**Comment by benjdudas** [comment]
@feisa if you are on 2.10 then you would have to be using the collection already. You may want to check if you have the most recent version on ansible.netcommon installed

**Comment by benjdudas** [comment]
@NilashishC just tested with `ansible.netcommon:1.4.1` and it does appear to be fixed.

**Comment by NilashishC** [comment]
@benjdudas @feisa It should be fixed starting from ansible.netcommon 1.1.0.

**Comment by feisa** [comment]
@NilashishC @benjdudas looks like this issue is still present

**Comment by NilashishC** [comment]
@feisa could you please confirm the following:

ansible version
ansible.netcommon version
value of `ansible_connection` set

Thank you.

**Comment by NilashishC** [comment]
@feisa Since we haven't heard from you yet, we're assuming you're no longer facing this issue. As such we'll be closing this ticket. If you still encounter this problem, please feel free to re-open this. Thank you!
